### ISSUE TITLE
Sieht mir nach einem Geringverdiener-Projekt aus

### ISSUE THREAD

**Issue by saibamo** [RomanDietenmeier/lerny-app#3]

**Comment by RomanDietenmeier** [comment]
Wir Geringverdiener halten in schweren Zeiten zusammen 🤝🏼 und trotzen der Gewalt der grausamen freien Marktwirtschaft.

**Comment by saibamo** [comment]
Open Source Piss ich!

**Comment by RomanDietenmeier** [comment]
Also echt unerhört!!!!
